### ISSUE TITLE
[Bug] Model empty

### ISSUE THREAD

**Issue by Martin1887** [casbin/casbin-authz-plugin#7]
Hello.

I am trying to use this plugin but it does not load the model. Below I explain my tests and results. All my tests have been made in CentOS 7 with casbin 1.0.0 and casbin-authz-plugin master branch code. Could you please advise what is wrong in my configuration or how could the issue be solved? Very thanks in advance.

After compiling the plugin with `make` and `sudo make install`, systemctl daemon-reload and sudo systemctl start casbin-authz-plugin are executed to start the plugin service. However, the service fails with the following error:

```
● casbin-authz-plugin.service - Docker RBAC & ABAC Authorization Plugin based on Casbin
   Loaded: loaded (/usr/lib/systemd/system/casbin-authz-plugin.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-09-01 07:49:04 UTC; 7s ago
  Process: 3551 ExecStart=/usr/lib/docker/casbin-authz-plugin (code=exited, status=2)
 Main PID: 3551 (code=exited, status=2)

Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3551]: /home/centos/go_path/src/github.com/casbin/casbin/enforcer.go:109 +0xf6
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3551]: github.com/casbin/casbin.NewEnforcer(0xc82003be18, 0x1, 0x1, 0x7120e0)
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3551]: /home/centos/go_path/src/github.com/casbin/casbin/enforcer.go:86 +0xa57
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3551]: main.newPlugin(0x82fb80, 0xb, 0x2, 0x0, 0x0)
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3551]: /home/centos/go_path/src/github.com/casbin/casbin-authz-plugin/plugin.go:25 +0x102
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3551]: main.main()
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3551]: /home/centos/go_path/src/github.com/casbin/casbin-authz-plugin/main.go:30 +0x1ac
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal systemd[1]: casbin-authz-plugin.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal systemd[1]: Unit casbin-authz-plugin.service entered failed state.
Sep 01 07:49:04 ip-172-31-21-67.eu-west-1.compute.internal systemd[1]: casbin-authz-plugin.service failed.
```

I have overcome this issue pointing the config file with `-config` option in the `ExecStart` sentence of the `/etc/systemd/system/multi-user.target.wants/casbin-authz-plugin.service` file:

```
[Unit]
Description=Docker RBAC & ABAC Authorization Plugin based on Casbin
Before=docker.service
After=network.target casbin-authz-plugin.socket
Requires=casbin-authz-plugin.socket docker.service

[Service]
ExecStart=/usr/lib/docker/casbin-authz-plugin -config /usr/lib/docker/casbin.conf

[Install]
WantedBy=multi-user.target
```

Nevertheless, after `daemon-reload` and `systemctl restart`, the service starts but without model:

```
● casbin-authz-plugin.service - Docker RBAC & ABAC Authorization Plugin based on Casbin
   Loaded: loaded (/usr/lib/systemd/system/casbin-authz-plugin.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-09-01 07:51:08 UTC; 4s ago
 Main PID: 3625 (casbin-authz-pl)
   CGroup: /system.slice/casbin-authz-plugin.service
           └─3625 /usr/lib/docker/casbin-authz-plugin -config /usr/lib/docker/casbin.conf

Sep 01 07:51:08 ip-172-31-21-67.eu-west-1.compute.internal systemd[1]: Started Docker RBAC & ABAC Authorization Plugin based on Casbin.
Sep 01 07:51:08 ip-172-31-21-67.eu-west-1.compute.internal systemd[1]: Starting Docker RBAC & ABAC Authorization Plugin based on Casbin...
Sep 01 07:51:08 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: 2017/09/01 07:51:08 Casbin config: /usr/lib/docker/casbin.conf
Sep 01 07:51:08 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: 2017/09/01 07:51:08 [Model:]
```

/usr/lib/docker/casbin.conf:

```
# Example configuration file for casbin
# https://github.com/casbin/casbin
#
# This file follows the CONF format.
#

[default]
# The file path to the model:
model_path = /usr/lib/docker/basic_model.conf

# The persistent method for policy, can be two values: file or database.
# policy_backend = file
# policy_backend = database
policy_backend = file

[file]
# The file path to the policy:
policy_path = /usr/lib/docker/basic_policy.csv

[database]
driver = mysql
data_source = root:@tcp(127.0.0.1:3306)/
```

/usr/lib/docker/basic_model.conf:

```
[request_definition]
r = obj, act

[policy_definition]
p = obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.obj == p.obj && r.act == p.act
```

/usr/lib/docker/basic_policy.csv:

```
p, /_ping, GET
p, /v1.27/images/json, GET
```

When a docker command is executed (for instance `ps -a`), the following error appear in `journalctl -xe -u casbin-authz-plugin` (nil pointer error because the model is empty I have understood):
```

Sep 01 07:51:08 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: 2017/09/01 07:51:08 Casbin config: /usr/lib/docker/casbin.conf
Sep 01 07:51:08 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: 2017/09/01 07:51:08 [Model:]
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: 2017/09/01 07:52:19 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: goroutine 19 [running]:
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.(*conn).serve.func1(0xc820080380)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:1389 +0xc1
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: panic(0x7ae700, 0xc82000e090)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/runtime/panic.go:443 +0x4e9
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: github.com/casbin/casbin.(*Enforcer).Enforce(0xc820056640, 0xc82003d810, 0x2, 0x2, 0xc820059240)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /home/centos/go_path/src/github.com/casbin/casbin/enforcer.go:237 +0x20e5
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: main.(*CasbinAuthZPlugin).AuthZReq(0xc82005e080, 0x0, 0x0, 0x0, 0x0, 0xc8200591c8, 0x3, 0xc8200591e0, 0x6, 0x0, ...)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /home/centos/go_path/src/github.com/casbin/casbin-authz-plugin/plugin.go:41 +0x22b
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: github.com/docker/go-plugins-helpers/authorization.(*Handler).initMux.func1(0x0, 0x0, 0x0, 0x0, 0xc8200591c8, 0x3, 0xc8200591e0, 0x6, 0x0, 0x0, ...)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /home/centos/go_path/src/github.com/docker/go-plugins-helpers/authorization/api.go:118 +0x89
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: github.com/docker/go-plugins-helpers/authorization.(*Handler).handle.func1(0x7fe1a4d53b78, 0xc8200d04e0, 0xc8200e0000)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /home/centos/go_path/src/github.com/docker/go-plugins-helpers/authorization/api.go:139 +0x1da
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.HandlerFunc.ServeHTTP(0xc820059030, 0x7fe1a4d53b78, 0xc8200d04e0, 0xc8200e0000)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:1618 +0x3a
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.(*ServeMux).ServeHTTP(0xc82005b4a0, 0x7fe1a4d53b78, 0xc8200d04e0, 0xc8200e0000)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:1910 +0x17d
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.serverHandler.ServeHTTP(0xc820080200, 0x7fe1a4d53b78, 0xc8200d04e0, 0xc8200e0000)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:2081 +0x19e
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.(*conn).serve(0xc820080380)
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:1472 +0xf2e
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: created by net/http.(*Server).Serve
Sep 01 07:52:19 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:2137 +0x44e
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: 2017/09/01 07:52:34 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: goroutine 6 [running]:
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.(*conn).serve.func1(0xc8200f6400)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:1389 +0xc1
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: panic(0x7ae700, 0xc82000e090)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/runtime/panic.go:443 +0x4e9
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: github.com/casbin/casbin.(*Enforcer).Enforce(0xc820056640, 0xc82003d810, 0x2, 0x2, 0xc8200592e0)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /home/centos/go_path/src/github.com/casbin/casbin/enforcer.go:237 +0x20e5
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: main.(*CasbinAuthZPlugin).AuthZReq(0xc82005e080, 0x0, 0x0, 0x0, 0x0, 0xc820059290, 0x3, 0xc8200c6d80, 0x1c, 0x0, ...)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /home/centos/go_path/src/github.com/casbin/casbin-authz-plugin/plugin.go:41 +0x22b
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: github.com/docker/go-plugins-helpers/authorization.(*Handler).initMux.func1(0x0, 0x0, 0x0, 0x0, 0xc820059290, 0x3, 0xc8200c6d80, 0x1c, 0x0, 0x0, ...)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /home/centos/go_path/src/github.com/docker/go-plugins-helpers/authorization/api.go:118 +0x89
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: github.com/docker/go-plugins-helpers/authorization.(*Handler).handle.func1(0x7fe1a4d53b78, 0xc8200d0680, 0xc8200fc1c0)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /home/centos/go_path/src/github.com/docker/go-plugins-helpers/authorization/api.go:139 +0x1da
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.HandlerFunc.ServeHTTP(0xc820059030, 0x7fe1a4d53b78, 0xc8200d0680, 0xc8200fc1c0)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:1618 +0x3a
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.(*ServeMux).ServeHTTP(0xc82005b4a0, 0x7fe1a4d53b78, 0xc8200d0680, 0xc8200fc1c0)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:1910 +0x17d
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.serverHandler.ServeHTTP(0xc820080200, 0x7fe1a4d53b78, 0xc8200d0680, 0xc8200fc1c0)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:2081 +0x19e
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: net/http.(*conn).serve(0xc8200f6400)
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:1472 +0xf2e
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: created by net/http.(*Server).Serve
Sep 01 07:52:34 ip-172-31-21-67.eu-west-1.compute.internal casbin-authz-plugin[3625]: /usr/lib/golang/src/net/http/server.go:2137 +0x44e
```

**Comment by Martin1887** [comment]
I have solved the issue by myself loading the model in Go code modifying enforcer.go instead loading configuration files, but if this issue is a bug (instead a wrong configuration in my side) it would be desirable to be fixed.


Thanks and regards.

**Comment by hsluoyz** [comment]
Thanks for pointing this issue out. ``casbin.conf`` has been deprecated and removed from the recent Casbin versions. I will fix it by using the traditional model file and policy file way.

**Comment by hsluoyz** [comment]
This issue is fixed in: https://github.com/casbin/casbin-authz-plugin/commit/9a2256d121603a9226374f34c94a25b64abf8b57
